### ISSUE TITLE
Update theme template

### ISSUE THREAD

**Issue by Tahul** [nuxt/starter#183]
Following https://github.com/nuxt-themes/starter/issues/13;

I think https://github.com/nuxt/starter/tree/theme should be used as the most minimal way to start a theme!

That way, https://github.com/nuxt-themes/starter could reflect the way we build themes at NuxtLabs (with lots of opinionated choices), and keep that official template as minimal as possible for anyone to build its own way of doing it?

I would happily open a PR about this here, but I would love to get @pi0 opinion on what structure should we give to most minimal theme here?

- Is the `.playground` directory sufficient to you?
- How do you think should we push people to publish their theme?
	- We currently use NPM with Docus, and GitHub template for Studio deployments
- What is best setup for TS support inside `.playground` and root of project at the same time?

**Comment by Tahul** [comment]
Also would love to get @danielroe opinions on minimal structure for theme starter :)

**Comment by danielroe** [comment]
I think I think the first question is whether the `nuxt-themes` organisation on GH is for just NuxtLabs or community themes. (I'd be very open to it being the location for hosting community themes as well as more 'first-party' themes like `docus`, with a similar process for moving community themes into it.)

Either way, I think it makes sense to have both a minimal starter and a more opinionated one with Nuxt best practices built in.

**Comment by danielroe** [comment]
I would recommend:
* publishing via npm as a default - it's more secure for pinning versions than GitHub
* set `typescript.includeWorkspace=true` in a `.nuxtrc` in the playground to enable TS support across the root (and a `tsconfig.json` which extends from the playground).

Is there a reason you are suggesting `.playground` rather than `playground`?

**Comment by atinux** [comment]
For `.playground` it is to have it at the top of VS Code in order to show that it is not related to the normal Nuxt project (theme)

**Comment by danielroe** [comment]
The only issue is that often IDEs (and TS) will exclude any folder beginning with `.` from auto-complete and type support. We had to work around that to get types out of `.nuxt` but I expect you might encounter some issues.

**Comment by atinux** [comment]
Oh I see, then `_playground` might be better?

**Comment by danielroe** [comment]
Or we could also use a `srcDir` to have `src` and `playground` alongside each other?

**Comment by atinux** [comment]
The idea was to keep the theme look like a Nuxt project, we had another structure before with `theme/` and `template/` but after using it I was not comfortable with it at the end.

**Comment by pi0** [comment]
Having a minimal starter here would be fantastic so people can create various types of theme and app base stacks with their complete control! 

I think having one directory that keeps the entire starter boilerplate is essential. It makes the structure clear and also ensures to avoidance of accidentally leaking a dev dependency into the published base. 

Thinking outside of the box, since extends feature can be used for various stacks that are not essentially a _theme_, we might also make the name more generic like `nuxi init -t base` that initializes a nuxt base layer. It could be also `/base` and renamed to anything else as needed after initialization. I think this would also reduce confusion between the theme starter and this starter that is purposed for `extends` feature starter.

Regarding the recommended way to publish layers, at the moment npm publishing is best because it allows installing any dependencies from theme layer as well. As soon as giget/c12 have the feature to install dependencies for clonned layer, we should switch to git based extending. Extends feature idea to to **extend from a standard nuxt project** and be able to make and publish such templates as easy as possible without the knowledge and extra setup this way any level of user can create a nuxt base and adopt it. This also makes the distribution process easier for private projects and git tags are secure to pin the version and changes. Many frameworks including golang and denoland already use them.

**Comment by Tahul** [comment]
I really like the idea of having `layer` or `extends` starter.

I think `base` naming can be a bit misleading as it is a very generic naming.

I submitted #185 which is a starting point at having the most minimal starting point to create a Nuxt Extends publishable project.

I would love to have your feedbacks on it! :)

**Comment by atinux** [comment]
`layer` is a much better name indeed.

Regarding leaking a dev dependency, I am not sure to understand since it's clear that `dependencies` are used here.

**Comment by pi0** [comment]
Layer seems a good name for me too! (which can be in general introduced as Nuxt Layers). 

Regarding dependencies, if we want to make the layer the same as a normal nuxt project, they are usually defined in devDependencies.
